openapi: 3.1.0
info:
  title: Ingredient OAS
  description: Ingredient OAS
  version: 1.0.0
servers:
  - url: 'https//localhost:8080'

tags:
  - name: Ingredients
  - name: Dishes

paths:
  /ingredients:
    get:
      tags:
        - Ingredients
      description: Return list of ingredients
      responses:
        '200':
          description: List of ingredients
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Ingredient'

  /ingredients/{id}:
    get:
      tags:
        - Ingredients
      parameters:
        - $ref: '#/components/parameters/IdParam'
      description: Return an ingredient with id as parameter
      responses:
        '200':
          description: Ingredient with his id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ingredient'
        '404':
          $ref: '#/components/responses/IngredientNotFound'

  /ingredients/{id}/stock:
    get:
      tags:
        - Ingredients
      parameters:
        - $ref: '#/components/parameters/IdParam'
        - $ref: '#/components/parameters/TemporalAt'
        - $ref: '#/components/parameters/Unit'
      description: The stock value for the ingredient with the provided identifier at the specified time and unit
      responses:
        '200':
          description: Stock value of the ingredient with {id} at a moment
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StockValue'
        '400':
          $ref: '#/components/responses/BadParamRequest'
        '404':
          $ref: '#/components/responses/IngredientNotFound'

components:
  parameters:
    IdParam:
      name: id
      in: path
      required: true
      schema:
        type: integer
    TemporalAt:
      name: at
      in: query
      required: false
      schema:
        type: string
        format: date-time
        example: "2024-01-06T12:00:00Z"
    Unit:
      name: unit
      in: query
      required: false
      schema:
        $ref: '#/components/schemas/UnitType'

  responses:
    BadParamRequest:
      description : Parameter Missing
      content:
        text/plain:
          schema:
            type: string
            example: "Either mandatory query parameter `at` or `unit` is not provided."

    IngredientNotFound:
      description: Ingredient not found
      content:
        text/plain:
          schema:
            type: string
            example: "Ingredient.id=4 is not found"

  schemas:
    CategoryEnum:
      type: string
      enum:
        - VEGETABLE
        - ANIMAL
        - MARINE
        - DAIRY
        - OTHER
      example: ANIMAL

    DishTypeEnum:
      type: string
      enum:
        - START
        - MAIN
        - STARTER
        - DESSERT
      example: STARTER

    UnitType:
      type: string
      enum:
        - KG
        - PCS
        - L
      example: KG

    Ingredient:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: poulet
        category:
          $ref: '#/components/schemas/CategoryEnum'
        price:
          type: number
          format: double
          example: 9.2

    StockValue:
      type: object
      properties:
        value:
          type: number
          format: float
          example: 24.3
        unit:
          $ref: '#/components/schemas/UnitType'





  
